mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logged_out/', views.LogoutView.as_view(), name='logged_out'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/delete/<int:pk>/', views.UserProfileDeleteView.as_view(), name='edit_profile'),
    path('profile/change/<int:pk>/', views.UserProfileUpdateView.as_view(), name='delete_profile'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class UserProfile(AbstractUser):
    image = models.ImageField(upload_to='avatars/', verbose_name='Аватар')

    def __str__(self):
        return self.username

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    question_description = models.TextField(max_length=500, verbose_name='Описание вопроса')
    image = models.ImageField(upload_to='questions_images/', verbose_name='Изображение')
    question_votes = models.IntegerField(verbose_name="Количество проголосовавших", default=0)
    pub_date = models.DateTimeField('date published')

    def published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(seconds=1)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def percentage(self):
        percents = self.votes * 100 / self.question.question_votes
        return percents

    def __str__(self):
        return self.choice_text

class Vote(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

mysite/polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image', 'username']

class RegistrationUserForm(UserCreationForm):
    username = forms.CharField(label='Введите логин', widget=forms.TextInput)
    email = forms.EmailField(label='Введите Email', max_length=254)
    password1 = forms.CharField(label='Введите пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Введите повторно пароль', widget=forms.PasswordInput)
    avatar = forms.ImageField(label='Предоставьте ваше фото', widget=forms.ClearableFileInput)

    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'password1', 'password2', 'avatar']

mysite/polls/views.py
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, DeleteView
from .forms import UserProfileForm, RegistrationUserForm
from .models import Question, Choice, UserProfile, Vote
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.views import LoginView, LogoutView


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class ProfileView(generic.DetailView):
    model = UserProfile
    template_name = 'polls/templates/profile.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return get_object_or_404(UserProfile, username=self.request.user.username)


class UserProfileDeleteView(DeleteView):
    model = UserProfile
    success_url = reverse_lazy('polls:index')
    template_name = 'polls/templates/delete_profile.html'


class UserProfileUpdateView(UpdateView):
    model = UserProfile
    form_class = UserProfile
    success_url = reverse_lazy('polls:profile')
    template_name = 'polls/templates/edit_profile.html'


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/templates/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/templates/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/templates/detail.html', {
            'question': question,
            'error_message': 'Вы не сделали выбор'
        })
    else:
        if Vote.objects.filter(question=question, user=request.user).exists():
            return render(request, 'polls/results.html', {
                'question': question,
                'error_message': 'вы уже голосовали'
            })
        else:
            question.question_votes += 1
            question.save()
            selected_choice.votes += 1
            selected_choice.save()
            voted = Vote.objects.create(question=question, user=request.user)
            voted.save()

            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class LoginView(LoginView):
    template_name = 'polls/registration/login.html'
    success_url = reverse_lazy('profile')


class LogoutView(LogoutView):
    template_name = 'polls/index.html'


class RegistrationView(CreateView):
    form_class = RegistrationUserForm
    template_name = 'polls/registration/registration.html'
    success_url = reverse_lazy('index')

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% block title %}<title>Dultsev_RKIS_1</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rowdies:wght@400;700&family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
  <header class="header">
      {% block header %}
        <div class="header-content">
            <a class="header-content__item" href="{% url 'polls:index' %}">Главная</a>
            {% if user.is_authenticated %}
                <a class="header-content__item" href="{% url 'polls:profile' %}">Профиль</a>
            {% endif %}
        </div>
        <div class="header-content">
          {% if user.is_authenticated %}
              <a class="header-content__item" href="{% url 'polls:logged_out'%}">Выйти</a>
              {% else %}
                <a class="header-content__item" href="{% url 'polls:login'%}">Авторизация</a>
                <a class="header-content__item" href="{% url 'polls:registration'%}">Регистрация</a>
           {% endif %}
        </div>
      {% endblock %}
  </header>
  <main class="main">
    {% block content %}{% endblock %}
  </main>
</body>
</html>

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
    <h2 class="name__block">Опросы</h2>
    {% if question_list %}
        {{question.question_text}}
        <p> Краткое описание опроса: {{question.question_description|slice:':50' }}</p>
        <div class="questions">
            {% for question in latest_question_list %}
            <div class="questions__item">
                <p class="questions__item_descr">Тема опроса:</p>
                <a class="questions__item_link" href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
            </div>
            {% endfor %}
        </div>
    {% else %}
         <p>
             Нет вопросов!
         </p>
    {% endif %}
{% endblock %}

mysite/polls/templates/polls/templates/delete_profile.html
{% extends "polls/base.html" %}

{% block content %}
    <h2>Вы уверены, что хотите удалить аккаунт? Его не получится восстановить</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить аккаунт</button>
    </form>
{% endblock %}

mysite/polls/templates/polls/templates/detail.html
{% extends "polls/base.html" %}

{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{question.question_text}}</h1>
            </legend>
            <p>Описание опроса: {{question.question_description}}</p>
            <p>Изображение: <img src="{{ question.image.url }}" alt="Изображение" class="w-10"></p>
            {% if error_message %}
                <p> {{error_message}}</p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
                <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
            {% endfor %}
        </fieldset>
    <input type="submit" value="Vote">
    </form>
{% endblock %}

mysite/polls/templates/polls/templates/edit_profile.html
{% extends "polls/base.html" %}

{% block content %}
    <h2>Редактировать данные аккунта</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Редактировать</button>
    </form>
{% endblock %}

mysite/polls/templates/polls/templates/profile.html
{% extends "polls/base.html" %}

{% block content %}
    <img src="{{ profile.avatar.url }}" alt="Avatar">
    <p>Имя пользователь: {{ request.user.username }}</p>
    <a class="btn-option" href="{% url 'polls:edit_profile' profile.id %}">Редактировать данные аккаунта</a>
    <a class="btn-option" href="{% url 'polls:delete_profile' profile.id%}">Удалить аккаунт</a>
{% endblock %}

mysite/polls/templates/polls/templates/results.html
{% extends "polls/base.html" %}

{% block content %}
    <h1 class="name__block">{{ question.question_text }}</h1>
    <div>
        {% for choice in question.choice_set.all %}
        <p>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</p>
        {% endfor %}
    </div>
    <a class="btn-option" href="{% url 'polls:detail'  question.id %}">Выбрать еще раз? </a>
{% endblock %}